import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-nicu-case-rate-outlier-reconciliation",
  "engine": "recovery",
  "title": "NICU Case-Rate & Outlier Reconciliation",
  "shortTitle": "NICU Case-Rate and Outlier Reconciliation",
  "tagline": "Reconstruct high-cost neonatal reimbursement and recover omitted acuity, carve-out, stop-loss, and outlier revenue.",
  "industry": "Neonatal Revenue Integrity",
  "buyer": "Children’s hospitals and neonatal programs",
  "uiPort": 4649,
  "apiPort": 5649,
  "accent": "#c2410c",
  "currency": "USD",
  "primaryOutcome": "NICU Case-Rate & Outlier Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances in one accountable workflow. Reconstruct high-cost neonatal reimbursement and recover omitted acuity, carve-out, stop-loss, and outlier revenue.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "NICU Case-Rate & Outlier Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("payer-contract-library","NCR01","Payer contract library","Execute payer contract library using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed payer contract library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Payer contract library Reference","text","NCR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("neonatal-case-registry","NCR02","Neonatal case registry","Execute neonatal case registry using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed neonatal case registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Neonatal case registry Reference","text","NCR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("acuity-level-timeline","NCR03","Acuity level timeline","Execute acuity level timeline using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed acuity level timeline decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Acuity level timeline Reference","text","NCR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("daily-census-reconciliation","NCR04","Daily census reconciliation","Execute daily census reconciliation using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed daily census reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Daily census reconciliation Reference","text","NCR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("case-rate-episode-logic","NCR05","Case-rate episode logic","Execute case-rate episode logic using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed case-rate episode logic decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Case-rate episode logic Reference","text","NCR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("included-service-validation","NCR06","Included service validation","Execute included service validation using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed included service validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Included service validation Reference","text","NCR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("implant-carve-out-calculation","NCR07","Implant carve-out calculation","Execute implant carve-out calculation using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed implant carve-out calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Implant carve-out calculation Reference","text","NCR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("drug-carve-out-calculation","NCR08","Drug carve-out calculation","Execute drug carve-out calculation using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed drug carve-out calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Drug carve-out calculation Reference","text","NCR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("transport-carve-out-review","NCR09","Transport carve-out review","Execute transport carve-out review using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed transport carve-out review decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Transport carve-out review Reference","text","NCR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("outlier-threshold-calculation","NCR10","Outlier threshold calculation","Execute outlier threshold calculation using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed outlier threshold calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Outlier threshold calculation Reference","text","NCR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("stop-loss-calculation","NCR11","Stop-loss calculation","Execute stop-loss calculation using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed stop-loss calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Stop-loss calculation Reference","text","NCR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("claim-remittance-matching","NCR12","Claim remittance matching","Execute claim remittance matching using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed claim remittance matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Claim remittance matching Reference","text","NCR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("underpayment-detection","NCR13","Underpayment detection","Execute underpayment detection using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed underpayment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Underpayment detection Reference","text","NCR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("payer-appeal-workflow","NCR14","Payer appeal workflow","Execute payer appeal workflow using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed payer appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Payer appeal workflow Reference","text","NCR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]}),
feature("program-payer-analytics","NCR15","Program payer analytics","Execute program payer analytics using neonatal contracts, admissions, acuity levels, daily census, procedures, implants, pharmacy, case rates, carve-outs, outliers, claims, and remittances.","Produce a governed program payer analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Payer / Neonatal Case","text","Payer / Neonatal Case · Standard Case"],["caseReference","Program payer analytics Reference","text","NCR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",590000],["entitledAmount","Contract or Rule-Supported Entitlement","currency",713900],["domainDriver","NICU Level","select","Level II",["Level II","Level III","Level IV"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Payer contract library case","Neonatal case registry case","Acuity level timeline case","Daily census reconciliation case","Case-rate episode logic case"]})
]);
